security:
    encoders:
        Symfony\Component\Security\Core\User\User: plaintext
        WTW\UserBundle\Tests\Security\Core\User\User: plaintext
        FOS\UserBundle\Model\UserInterface: sha512

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    providers:
        chain_provider:
            chain:
                providers: [user_provider]
        in_memory:
            memory:
                users:
                    %api_wtw_repositories_user_name%:
                        password: '%api_wtw_repositories_password%'
                        roles: [ROLE_ADMIN]
                    %api_wtw_repositories_user_name_super%:
                        password: '%api_wtw_repositories_password%'
                        roles: [ROLE_SUPER_ADMIN]
        user_provider:
            entity:
                class:               WTWUserBundle:User
                property:            apiKey

    firewalls:
        # @see https://symfony.com/doc/current/security/multiple_guard_authenticators.html#multiple-authenticators-with-separate-entry-points
        auth0:
            pattern: '^/api/twitter/admin/lists'

            logout: ~

            guard:
                authenticators:
                    - app.auth0_token_authenticator

        main:
            anonymous: ~

            logout: ~

            guard:
                authenticators:
                    - app.token_authenticator

    access_control:
        - { path: ^/api,          role: ROLE_USER }
