services:
    App\Api\AccessToken\TokenChange:
        class: 'App\Api\AccessToken\TokenChange'
        arguments:
            - '@repository.access_token'
            - '@logger'

    App\Infrastructure\Twitter\Api\Accessor\OwnershipAccessor:
        class: 'App\Infrastructure\Twitter\Api\Accessor\OwnershipAccessor'
        arguments:
            - '@App\Twitter\Api\Accessor'
            - '@repository.access_token'
            - '@App\Api\AccessToken\TokenChange'
            - '@logger'
        calls:
            - [ 'setOwnershipBatchCollectedEventRepository', [ '@App\Infrastructure\Collection\Repository\OwnershipBatchCollectedEventRepository'] ]

    App\Infrastructure\Twitter\Api\Accessor\FriendsListAccessor:
        class: 'App\Infrastructure\Twitter\Api\Accessor\FriendsListAccessor'
        arguments:
            - '@App\Twitter\Api\Accessor'
            - '@logger'

    App\Infrastructure\Twitter\Api\Mutator\FriendshipMutator:
        class: 'App\Infrastructure\Twitter\Api\Mutator\FriendshipMutator'
        calls:
            - [ 'setApiAccessor', [ '@App\Twitter\Api\Accessor' ] ]

    App\Infrastructure\Twitter\Api\Accessor\MemberProfileAccessor:
        class: 'App\Infrastructure\Twitter\Api\Accessor\MemberProfileAccessor'
        arguments:
            - '@App\Twitter\Api\Accessor'
            - '@user_manager'
            - '@App\Infrastructure\Twitter\Api\UnavailableResourceHandler'
        calls:
            - [ 'setMemberProfileCollectedEventRepository', [ '@App\Infrastructure\Collection\Repository\MemberProfileCollectedEventRepository'] ]