parameters:
    command.map_aggregate_status_collection.class:                              'App\StatusCollection\Mapping\Command\MapAggregateStatusCollectionCommand'
    command.map_status_collection.class:                                        'App\StatusCollection\Mapping\Command\MapStatusCollectionCommand'
    command.select_status_collection.class:                                     'App\StatusCollection\Command\SelectStatusCollectionCommand'
    command.add_members_to_aggregate.class:                                     'App\Member\Command\AddMemberToAggregateCommand'
    command.import_network.class:                                               'App\Member\Command\ImportNetworkCommand'
    weaving_the_web_amqp.consumer.conversation_status.class:                    'App\Conversation\Consumer\ConversationStatusConsumer'
    weaving_the_web_amqp.producer.produce_conversation_messages_command.class:  'App\Conversation\Producer\ProduceConversationMessagesCommand'
    weaving_the_web_amqp.producer.produce_timely_status_messages_command.class: 'App\Aggregate\Producer\ProduceTimelyStatusMessagesCommand'
    weaving_the_web_amqp.producer.produce_member_messages_command.class:        'App\Conversation\Producer\ProduceMemberMessagesCommand'
    weaving_the_web_amqp.consumer.status.class:                                 'App\Amqp\Twitter\UserStatus'
    weaving_the_web_amqp.consumer.timely_status.class:                          'App\Aggregate\Consumer\TimelyStatusConsumer'
    weaving_the_web_amqp.consumer.network.class:                                'App\Member\Consumer\NetworkConsumer'
    press_review.fetch_member_status.class:                                     'App\Amqp\Command\FetchMemberStatusMessageDispatcher'

services:
    command.import_media_relationships:
        class: 'App\Media\Command\ImportMediaRelationshipsCommand'
        properties:
            logger:          '@logger'
            mediasDirectory: '%kernel.project_dir%/../src/App/Resources/medias'
            mediaRepository: '@repository.media'
            ownerRepository: '@repository.owner'
        tags:
            - { name: 'console.command' }

    command.select_status_collection:
        class:                      "%command.select_status_collection.class%"
        properties:
            statusRepository:       "@weaving_the_web_twitter.repository.status"
        tags:
            - { name: 'console.command' }

    command.add_members_to_aggregate:
        class:                      "%command.add_members_to_aggregate.class%"
        properties:
            aggregateRepository:                "@weaving_the_web_twitter.repository.aggregate"
            aggregateSubscriptionRepository:    "@repository.aggregate_subscription"
            accessor:                           "@weaving_the_web_twitter.api_accessor"
            logger:                             "@logger"
            userRepository:                     "@user_manager"
        tags:
            - { name: 'console.command' }

#    command.import_network:
#        class:                 "%command.import_network.class%"
#        properties:
#            networkRepository: '@repository.network'
#            producer:          '@old_sound_rabbit_mq.weaving_the_web_amqp.producer.network_producer'
#        tags:
#            - { name: 'console.command' }

    command.import_member_aggregates:
        class:                                      'App\Aggregate\Command\ImportMemberAggregatesCommand'
        properties:
            accessor:                               '@weaving_the_web_twitter.api_accessor'
            aggregateSubscriptionRepository:        '@repository.aggregate_subscription'
            logger:                                 '@logger'
            memberAggregateSubscriptionRepository:  '@repository.member_aggregate_subscription'
            networkRepository:                      '@repository.network'
            memberRepository:                       "@user_manager"
        tags:
            - { name: 'console.command' }

    command.map_status_collection:
        class:                      "%command.map_status_collection.class%"
        properties:
            statusRepository:       "@weaving_the_web_twitter.repository.status"
            refreshStatusMapping:   "@mapping.refresh_status"
            oauthToken:             "%weaving_the_web_twitter.oauth_token.default%"
            oauthSecret:            "%weaving_the_web_twitter.oauth_secret.default%"
        tags:
            - { name: 'console.command' }

    command.map_aggregate_status_collection:
        class:                      "%command.map_aggregate_status_collection.class%"
        properties:
            logger:                             "@monolog.logger.status"
            statusRepository:                   "@weaving_the_web_twitter.repository.status"
            refreshStatusMapping:               "@mapping.refresh_status"
            oauthToken:                         "%weaving_the_web_twitter.oauth_token.default%"
            oauthSecret:                        "%weaving_the_web_twitter.oauth_secret.default%"
            searchMatchingStatusRepository:     '@repository.search_matching_status'
            timeAfterWhichOperationIsSkipped:   '%env(resolve:OPERATIONS_SKIPPED_AFTER)%'
            timeBeforeWhichOperationIsSkipped:  '%env(resolve:OPERATIONS_SKIPPED_BEFORE)%'
        tags:
            - { name: 'console.command' }

    command.recommend_subscriptions:
        class:                  'App\Recommendation\Command\RecommendSubscriptionsCommand'
        properties:
            entityManager:      '@doctrine.orm.entity_manager'
        tags:
            - { name: 'console.command' }

    command.subscribe_to_member_timelines:
        class:                               'App\Member\Command\SubscribeToMemberTimelinesCommand'
        properties:
            accessor:                        '@weaving_the_web_twitter.api_accessor'
            aggregateSubscriptionRepository: '@repository.aggregate_subscription'
            logger:                          '@logger'
        tags:
            - { name: 'console.command' }

    weaving_the_web_amqp.consumer.conversation_status:
        class:                        "%weaving_the_web_amqp.consumer.conversation_status.class%"
        calls:
            - [ 'setLogger',            [ '@monolog.logger.status'] ]
            - [ 'setUserRepository',    [ '@user_manager'] ]
        properties:
            aggregateRepository:    "@weaving_the_web_twitter.repository.aggregate"
            entityManager:          "@doctrine.orm.entity_manager"
            operationClock:         "@operation.clock"
            statusAccessor:         "@weaving_the_web.accessor.status"
            statusRepository:       "@weaving_the_web_twitter.repository.status"

    weaving_the_web_amqp.consumer.timely_status:
        class:                        "%weaving_the_web_amqp.consumer.timely_status.class%"
        calls:
            - [ 'setLogger',            [ '@monolog.logger.status'] ]
            - [ 'setUserRepository',    [ '@user_manager'] ]
        properties:
            aggregateRepository:    "@weaving_the_web_twitter.repository.aggregate"
            entityManager:          "@doctrine.orm.entity_manager"
            statusAccessor:         "@weaving_the_web.accessor.status"
            timelyStatusRepository: "@repository.timely_status"

    weaving_the_web_amqp.consumer.network:
        class:                      "%weaving_the_web_amqp.consumer.network.class%"
        properties:
            networkRepository:      "@repository.network"
            logger:                 "@logger"

    weaving_the_web_amqp.twitter:
        class:                       "%weaving_the_web_amqp.consumer.status.class%"
        properties:
            operationClock:          "@operation.clock"
            tokenRepository:         "@weaving_the_web_api.repository.token"
        calls:
            - [ 'setLogger',            [ '@monolog.logger.status'] ]

    weaving_the_web_amqp.consumer.status:
        class:                        "%weaving_the_web_amqp.consumer.status.class%"
        calls:
            - [ 'setSerializer',        [ '@weaving_the_web_twitter.serializer.user_status'] ]
            - [ 'setLogger',            [ '@monolog.logger.status'] ]
            - [ 'setUserRepository',    [ '@user_manager'] ]
        properties:
            operationClock:             "@operation.clock"
            tokenRepository:            "@weaving_the_web_api.repository.token"

    weaving_the_web_amqp.producer.conversation_status:
        class:               "%weaving_the_web_amqp.producer.produce_conversation_messages_command.class%"
        properties:
            operationClock:  "@operation.clock"
            filesystem:      "@filesystem"
            statusDirectory: "%kernel.project_dir%/../src/App/Resources/statuses"
        tags:
            - { name: 'console.command' }

    weaving_the_web_amqp.producer.timely_status:
        class:               "%weaving_the_web_amqp.producer.produce_timely_status_messages_command.class%"
        properties:
            statusDirectory: "%kernel.project_dir%/../src/App/Resources/statuses"
        tags:
            - { name: 'console.command' }

    weaving_the_web_amqp.producer.member_status:
        class:               "%weaving_the_web_amqp.producer.produce_member_messages_command.class%"
        properties:
            operationClock:  "@operation.clock"
            statusDirectory: "%kernel.project_dir%/../src/App/Resources/statuses"
        tags:
            - { name: 'console.command' }

    press_review.fetch_member_status:
        class:                              "%press_review.fetch_member_status.class%"
        properties:
            operationClock:                 "@operation.clock"
            savedSearchRepository:          "@repository.saved_search"
            searchMatchingStatusRepository: "@repository.search_matching_status"
        calls:
            - [ 'setAccessor',              [ '@weaving_the_web_twitter.api_accessor'] ]
            - [ 'setDefaultSecret',         [ '%weaving_the_web_twitter.oauth_secret.default%'] ]
            - [ 'setDefaultToken',          [ '%weaving_the_web_twitter.oauth_token.default%'] ]
            - [ 'setMessageBus',            [ '@messenger.default_bus'] ]
            - [ 'setTokenRepository',       [ '@weaving_the_web_api.repository.token'] ]
            - [ 'setTranslator',            [ '@translator'] ]
            - [ 'setMemberRepository',      [ '@user_manager'] ]
            - [ 'setAggregateRepository',   [ '@repository.aggregate'] ]
            - [ 'setEntityManager',         [ '@doctrine.orm.entity_manager'] ]
            - [ 'setLogger',                [ '@logger'] ]
        tags:
            - { name: 'console.command' }

