parameters:
    command.map_aggregate_status_collection.class:                              'App\StatusCollection\Mapping\Command\MapAggregateStatusCollectionCommand'
    command.map_status_collection.class:                                        'App\StatusCollection\Mapping\Command\MapStatusCollectionCommand'
    command.select_status_collection.class:                                     'App\StatusCollection\Command\SelectStatusCollectionCommand'
    command.add_members_to_aggregate.class:                                     'App\Member\Command\AddMemberToAggregateCommand'
    command.import_network.class:                                               'App\Member\Command\ImportNetworkCommand'
    weaving_the_web_amqp.consumer.conversation_status.class:                    'App\Conversation\Consumer\ConversationStatusConsumer'
    weaving_the_web_amqp.producer.produce_conversation_messages_command.class:  'App\Conversation\Producer\ProduceConversationMessagesCommand'
    weaving_the_web_amqp.producer.produce_timely_status_messages_command.class: 'App\Aggregate\Producer\ProduceTimelyStatusMessagesCommand'
    weaving_the_web_amqp.producer.produce_member_messages_command.class:        'App\Conversation\Producer\ProduceMemberMessagesCommand'
    press_review.publication_message.handler:                                   'App\Amqp\MessageHandler\FetchPublicationMessageHandler'
    weaving_the_web_amqp.consumer.network.class:                                'App\Member\Consumer\NetworkConsumer'
    press_review.fetch_member_status.class:                                     'App\Amqp\Command\FetchPublicationMessageDispatcher'

services:
    App\Amqp\Command\FetchPublicationMessageDispatcher:
        class:                              "%press_review.fetch_member_status.class%"
        properties:
            operationClock:                 '@operation.clock'
            savedSearchRepository:          '@repository.saved_search'
            searchMatchingStatusRepository: '@repository.search_matching_status'
        calls:
            - [ 'setAccessor',                      [ '@App\Twitter\Api\Accessor'] ]
            - [ 'setAggregateRepository',           [ '@App\Api\Repository\PublicationListRepository'] ]
            - [ 'setDefaultSecret',                 [ '%weaving_the_web_twitter.oauth_secret.default%'] ]
            - [ 'setDefaultToken',                  [ '%weaving_the_web_twitter.oauth_token.default%'] ]
            - [ 'setTokenRepository',               [ '@repository.access_token'] ]
            - [ 'setPublicationMessageDispatcher',  [ '@App\Infrastructure\Amqp\MessageBus\PublicationMessageDispatcher'] ]
            - [ 'setTranslator',                    [ '@App\Infrastructure\Translation\Translator'] ]
            - [ 'setEntityManager',                 [ '@doctrine.orm.entity_manager'] ]
            - [ 'setLogger',                        [ '@logger'] ]
        tags:
            - { name: 'console.command' }
        public: true

    App\Amqp\Command\FetchMemberSubscriptionTimelineMessageDispatcher:
        class: 'App\Amqp\Command\FetchMemberSubscriptionTimelineMessageDispatcher'
        calls:
            - [ 'setAccessor',                              [ '@App\Twitter\Api\Accessor'] ]
            - [ 'setAggregateRepository',                   [ '@App\Api\Repository\PublicationListRepository'] ]
            - [ 'setDefaultSecret',                         [ '%weaving_the_web_twitter.oauth_secret.default%'] ]
            - [ 'setDefaultToken',                          [ '%weaving_the_web_twitter.oauth_token.default%'] ]
            - [ 'setEntityManager',                         [ '@doctrine.orm.entity_manager'] ]
            - [ 'setLogger',                                [ '@logger'] ]
            - [ 'setMemberFriendsCollectedEventRepository', [ '@App\Infrastructure\Collection\Repository\MemberFriendsCollectedEventRepository'] ]
            - [ 'setMemberProfileCollectedEventRepository', [ '@App\Infrastructure\Collection\Repository\MemberProfileCollectedEventRepository'] ]
            - [ 'setMemberRepository',                      [ '@App\Infrastructure\Repository\Membership\MemberRepository'] ]
            - [ 'setMessageBus',                            [ '@messenger.default_bus'] ]
            - [ 'setTranslator',                            [ '@translator'] ]
        tags:
            - { name: 'console.command' }
        public: true

    press_review.fetch_status:
        class:                        "%press_review.publication_message.handler%"
        calls:
            - [ 'setCollector',         [ '@App\Infrastructure\Twitter\Collector\PublicationCollector'] ]
            - [ 'setLogger',            [ '@monolog.logger.status'] ]
            - [ 'setUserRepository',    [ '@user_manager'] ]
        properties:
            operationClock:             '@operation.clock'
            tokenRepository:            '@repository.access_token'
        tags:
            -
                name: messenger.message_handler
                handles: App\Infrastructure\Amqp\Message\FetchMemberStatus

    press_review.fetch_likes:
        class:                          "%press_review.publication_message.handler%"
        calls:
            - [ 'setCollector',         [ '@App\Infrastructure\Twitter\Collector\PublicationCollector'] ]
            - [ 'setLogger',            [ '@monolog.logger.status'] ]
            - [ 'setUserRepository',    [ '@user_manager'] ]
        properties:
            operationClock:             '@operation.clock'
            tokenRepository:            '@repository.access_token'
        tags:
            -
                name: messenger.message_handler
                handles: App\Infrastructure\Amqp\Message\FetchMemberLikes

    App\Twitter\Command\MigrateStatusToPublicationsCommand:
        class:  '\App\Twitter\Command\MigrateStatusToPublicationsCommand'
        calls:
            - [ 'setPublicationRepository', [ '@App\Twitter\Repository\PublicationRepository' ] ]
        tags:
            - { name: 'console.command' }

    command.import_media_relationships:
        class: 'App\Media\Command\ImportMediaRelationshipsCommand'
        properties:
            logger:          '@logger'
            mediasDirectory: '%kernel.project_dir%/../src/App/Resources/medias'
            mediaRepository: '@repository.media'
            ownerRepository: '@repository.owner'
        tags:
            - { name: 'console.command' }

    command.select_status_collection:
        class:                      "%command.select_status_collection.class%"
        properties:
            statusRepository: '@App\Api\Repository\StatusRepository'
        tags:
            - { name: 'console.command' }

    command.add_members_to_aggregate:
        class:                      "%command.add_members_to_aggregate.class%"
        properties:
            aggregateRepository:                '@App\Api\Repository\PublicationListRepository'
            aggregateSubscriptionRepository:    '@repository.publication_list_subscription'
            accessor:                           '@App\Twitter\Api\Accessor'
            logger:                             '@logger'
            userRepository:                     '@user_manager'
        tags:
            - { name: 'console.command' }

    command.import_network:
        class:                 "%command.import_network.class%"
        properties:
            networkRepository: '@repository.network'
            #
            #
            # TODO
            # Replace rabbimq bundle messager producer with
            # symfony component message dispatcher
            #
            # producer:          '@old_sound_rabbit_mq.weaving_the_web_amqp.producer.network_producer'
        tags:
            - { name: 'console.command' }

    command.import_member_aggregates:
        class:                                      'App\Aggregate\Command\ImportMemberAggregatesCommand'
        properties:
            accessor:                               '@App\Twitter\Api\Accessor'
            aggregateSubscriptionRepository:        '@repository.publication_list_subscription'
            logger:                                 '@logger'
            memberAggregateSubscriptionRepository:  '@repository.member_aggregate_subscription'
            networkRepository:                      '@repository.network'
            memberRepository:                       '@user_manager'
        tags:
            - { name: 'console.command' }

    command.map_status_collection:
        class:                      "%command.map_status_collection.class%"
        properties:
            statusRepository:       '@App\Api\Repository\StatusRepository'
            refreshStatusMapping:   '@mapping.refresh_status'
            oauthToken:             "%weaving_the_web_twitter.oauth_token.default%"
            oauthSecret:            "%weaving_the_web_twitter.oauth_secret.default%"
        tags:
            - { name: 'console.command' }

    command.map_aggregate_status_collection:
        class:                      "%command.map_aggregate_status_collection.class%"
        properties:
            logger:                             '@monolog.logger.status'
            statusRepository:                   '@App\Api\Repository\StatusRepository'
            refreshStatusMapping:               '@mapping.refresh_status'
            oauthToken:                         "%weaving_the_web_twitter.oauth_token.default%"
            oauthSecret:                        "%weaving_the_web_twitter.oauth_secret.default%"
            searchMatchingStatusRepository:     '@repository.search_matching_status'
            timeAfterWhichOperationIsSkipped:   '%env(resolve:OPERATIONS_SKIPPED_AFTER)%'
            timeBeforeWhichOperationIsSkipped:  '%env(resolve:OPERATIONS_SKIPPED_BEFORE)%'
        tags:
            - { name: 'console.command' }

    command.recommend_subscriptions:
        class:                  'App\Recommendation\Command\RecommendSubscriptionsCommand'
        properties:
            entityManager:      '@doctrine.orm.entity_manager'
        tags:
            - { name: 'console.command' }

    command.subscribe_to_member_timelines:
        class:                               'App\Member\Command\SubscribeToMemberTimelinesCommand'
        properties:
            accessor:                        '@App\Twitter\Api\Accessor'
            aggregateSubscriptionRepository: '@repository.publication_list_subscription'
            logger:                          '@logger'
        tags:
            - { name: 'console.command' }

    weaving_the_web_amqp.consumer.conversation_status:
        class:                        "%weaving_the_web_amqp.consumer.conversation_status.class%"
        calls:
            - [ 'setLogger',            [ '@monolog.logger.status'] ]
            - [ 'setStatusAccessor',    [ '@App\Accessor\StatusAccessor' ] ]
            - [ 'setStatusRepository',  [ '@App\Api\Repository\StatusRepository' ] ]
            - [ 'setUserRepository',    [ '@user_manager'] ]
        properties:
            aggregateRepository:    '@App\Api\Repository\PublicationListRepository'
            entityManager:          '@doctrine.orm.entity_manager'
            operationClock:         '@operation.clock'

    weaving_the_web_amqp.consumer.network:
        class:                      "%weaving_the_web_amqp.consumer.network.class%"
        properties:
            networkRepository:      '@repository.network'
            logger:                 '@logger'

    weaving_the_web_amqp.twitter:
        class:                       "%press_review.publication_message.handler%"
        properties:
            operationClock:          '@operation.clock'
            tokenRepository:         '@repository.access_token'
        calls:
            - [ 'setLogger',            [ '@monolog.logger.status'] ]

    weaving_the_web_amqp.producer.conversation_status:
        class:               "%weaving_the_web_amqp.producer.produce_conversation_messages_command.class%"
        properties:
            operationClock:  '@operation.clock'
            filesystem:      '@filesystem'
            statusDirectory: "%kernel.project_dir%/../src/App/Resources/statuses"
        tags:
            - { name: 'console.command' }

    weaving_the_web_amqp.producer.timely_status:
        class:               "%weaving_the_web_amqp.producer.produce_timely_status_messages_command.class%"
        properties:
            statusDirectory: "%kernel.project_dir%/../src/App/Resources/statuses"
        tags:
            - { name: 'console.command' }

    weaving_the_web_amqp.producer.member_status:
        class:               "%weaving_the_web_amqp.producer.produce_member_messages_command.class%"
        properties:
            operationClock:  '@operation.clock'
            statusDirectory: "%kernel.project_dir%/../src/App/Resources/statuses"
        tags:
            - { name: 'console.command' }
