parameters:
    doctrine_extensions_dql:
        datetime_functions:
            convert_tz: DoctrineExtensions\Query\Mysql\ConvertTz
            date: DoctrineExtensions\Query\Mysql\Date
            date_format: DoctrineExtensions\Query\Mysql\DateFormat
            dateadd: DoctrineExtensions\Query\Mysql\DateAdd
            datesub: DoctrineExtensions\Query\Mysql\DateSub
            datediff: DoctrineExtensions\Query\Mysql\DateDiff
            day: DoctrineExtensions\Query\Mysql\Day
            dayname: DoctrineExtensions\Query\Mysql\DayName
            dayofweek: DoctrineExtensions\Query\Mysql\DayOfWeek
            dayofyear: DoctrineExtensions\Query\Mysql\DayOfYear
            div: DoctrineExtensions\Query\Mysql\Div
            from_unixtime: DoctrineExtensions\Query\Mysql\FromUnixtime
            hour: DoctrineExtensions\Query\Mysql\Hour
            last_day: DoctrineExtensions\Query\Mysql\LastDay
            minute: DoctrineExtensions\Query\Mysql\Minute
            now: DoctrineExtensions\Query\Mysql\Now
            month: DoctrineExtensions\Query\Mysql\Month
            monthname: DoctrineExtensions\Query\Mysql\MonthName
            period_diff: DoctrineExtensions\Query\Mysql\PeriodDiff
            second: DoctrineExtensions\Query\Mysql\Second
            sectotime: DoctrineExtensions\Query\Mysql\SecToTime
            strtodate: DoctrineExtensions\Query\Mysql\StrToDate
            time: DoctrineExtensions\Query\Mysql\Time
            timediff: DoctrineExtensions\Query\Mysql\TimeDiff
            timestampadd: DoctrineExtensions\Query\Mysql\TimestampAdd
            timestampdiff: DoctrineExtensions\Query\Mysql\TimestampDiff
            timetosec: DoctrineExtensions\Query\Mysql\TimeToSec
            week: DoctrineExtensions\Query\Mysql\Week
            weekday: DoctrineExtensions\Query\Mysql\WeekDay
            year: DoctrineExtensions\Query\Mysql\Year
            yearmonth: DoctrineExtensions\Query\Mysql\YearMonth
            yearweek: DoctrineExtensions\Query\Mysql\YearWeek
            unix_timestamp: DoctrineExtensions\Query\Mysql\UnixTimestamp
            utc_timestamp: DoctrineExtensions\Query\Mysql\UtcTimestamp
            extract: DoctrineExtensions\Query\Mysql\Extract

        numeric_functions:
            acos: DoctrineExtensions\Query\Mysql\Acos
            asin: DoctrineExtensions\Query\Mysql\Asin
            atan2: DoctrineExtensions\Query\Mysql\Atan2
            atan: DoctrineExtensions\Query\Mysql\Atan
            bit_count: DoctrineExtensions\Query\Mysql\BitCount
            bit_xor: DoctrineExtensions\Query\Mysql\BitXor
            ceil: DoctrineExtensions\Query\Mysql\Ceil
            cos: DoctrineExtensions\Query\Mysql\Cos
            cot: DoctrineExtensions\Query\Mysql\Cot
            degrees: DoctrineExtensions\Query\Mysql\Degrees
            exp: DoctrineExtensions\Query\Mysql\Exp
            floor: DoctrineExtensions\Query\Mysql\Floor
            log: DoctrineExtensions\Query\Mysql\Log
            log10: DoctrineExtensions\Query\Mysql\Log10
            log2: DoctrineExtensions\Query\Mysql\Log2
            pi: DoctrineExtensions\Query\Mysql\Pi
            power: DoctrineExtensions\Query\Mysql\Power
            quarter: DoctrineExtensions\Query\Mysql\Quarter
            radians: DoctrineExtensions\Query\Mysql\Radians
            rand: DoctrineExtensions\Query\Mysql\Rand
            round: DoctrineExtensions\Query\Mysql\Round
            stddev: DoctrineExtensions\Query\Mysql\StdDev
            sin: DoctrineExtensions\Query\Mysql\Sin
            std: DoctrineExtensions\Query\Mysql\Std
            tan: DoctrineExtensions\Query\Mysql\Tan
            variance: DoctrineExtensions\Query\Mysql\Variance

        string_functions:
            aes_decrypt: DoctrineExtensions\Query\Mysql\AesDecrypt
            aes_encrypt: DoctrineExtensions\Query\Mysql\AesEncrypt
            any_value: DoctrineExtensions\Query\Mysql\AnyValue
            ascii: DoctrineExtensions\Query\Mysql\Ascii
            binary: DoctrineExtensions\Query\Mysql\Binary
            cast: Oro\ORM\Query\AST\Functions\Cast
            char_length: DoctrineExtensions\Query\Mysql\CharLength
            collate: DoctrineExtensions\Query\Mysql\Collate
            concat_ws: DoctrineExtensions\Query\Mysql\ConcatWs
            countif: DoctrineExtensions\Query\Mysql\CountIf
            crc32: DoctrineExtensions\Query\Mysql\Crc32
            degrees: DoctrineExtensions\Query\Mysql\Degrees
            field: DoctrineExtensions\Query\Mysql\Field
            find_in_set: DoctrineExtensions\Query\Mysql\FindInSet
            greatest: DoctrineExtensions\Query\Mysql\Greatest
            group_concat: DoctrineExtensions\Query\Mysql\GroupConcat
            hex: DoctrineExtensions\Query\Mysql\Hex
            ifelse: DoctrineExtensions\Query\Mysql\IfElse
            ifnull: DoctrineExtensions\Query\Mysql\IfNull
            inet_aton: DoctrineExtensions\Query\Mysql\InetAton
            inet_ntoa: DoctrineExtensions\Query\Mysql\InetNtoa
            inet6_aton: DoctrineExtensions\Query\Mysql\Inet6Aton
            inet6_ntoa: DoctrineExtensions\Query\Mysql\Inet6Ntoa
            instr: DoctrineExtensions\Query\Mysql\Instr
            is_ipv4: DoctrineExtensions\Query\Mysql\IsIpv4
            is_ipv4_compat: DoctrineExtensions\Query\Mysql\IsIpv4Compat
            is_ipv4_mapped: DoctrineExtensions\Query\Mysql\IsIpv4Mapped
            is_ipv6: DoctrineExtensions\Query\Mysql\IsIpv6
            least: DoctrineExtensions\Query\Mysql\Least
            lpad: DoctrineExtensions\Query\Mysql\Lpad
            match: DoctrineExtensions\Query\Mysql\MatchAgainst
            md5: DoctrineExtensions\Query\Mysql\Md5
            nullif: DoctrineExtensions\Query\Mysql\NullIf
            radians: DoctrineExtensions\Query\Mysql\Radians
            regexp: DoctrineExtensions\Query\Mysql\Regexp
            replace: DoctrineExtensions\Query\Mysql\Replace
            rpad: DoctrineExtensions\Query\Mysql\Rpad
            sha1: DoctrineExtensions\Query\Mysql\Sha1
            sha2: DoctrineExtensions\Query\Mysql\Sha2
            soundex: DoctrineExtensions\Query\Mysql\Soundex
            str_to_date: DoctrineExtensions\Query\Mysql\StrToDate
            substring_index: DoctrineExtensions\Query\Mysql\SubstringIndex
            unhex: DoctrineExtensions\Query\Mysql\Unhex
            uuid_short: DoctrineExtensions\Query\Mysql\UuidShort
            json_extract: Scienta\DoctrineJsonFunctions\Query\AST\Functions\Mysql\JsonExtract

doctrine:
    dbal:
        connections:
            default:
                url: '%env(resolve:DATABASE_URL)%'
                logging: false
        types:
            uuid:            Ramsey\Uuid\Doctrine\UuidType
            correlation_id:  App\Twitter\Infrastructure\Operation\Correlation\CorrelationIdType
    orm:
        default_entity_manager:         default
        auto_generate_proxy_classes:    true
        entity_managers:
            default:
                naming_strategy:        doctrine.orm.naming_strategy.underscore_number_aware
                auto_mapping:           false
                connection:             default
                dql:                    "%doctrine_extensions_dql%"
                mappings:

                    Api:
                        alias:      'Api'
                        is_bundle:  false
                        dir:        '%kernel.project_dir%/src/Twitter/Infrastructure/Http/Entity'
                        prefix:     'App\Twitter\Infrastructure\Http\Entity'
                        type:       annotation

                    FollowersListCollectedEvent:
                        alias:      'FollowersListCollectedEvent'
                        dir:        '%kernel.project_dir%/config/model/curation'
                        is_bundle:  false
                        prefix:     App\Twitter\Infrastructure\Curation\Entity
                        type:       xml

                    FriendsListCollectedEvent:
                        alias:      'FriendsListCollectedEvent'
                        dir:        '%kernel.project_dir%/config/model/curation'
                        is_bundle:  false
                        prefix:     App\Twitter\Infrastructure\Curation\Entity
                        type:       xml

                    MembersList:
                        alias:      'MembersList'
                        dir:        '%kernel.project_dir%/src/Ownership/Domain/Entity'
                        is_bundle:  false
                        prefix:     'App\Ownership\Domain\Entity'
                        type:       annotation

                    MemberProfileCollectedEvent:
                        alias:      'MemberProfileCollectedEvent'
                        dir:        '%kernel.project_dir%/config/model/curation'
                        is_bundle:  false
                        prefix:     App\Twitter\Infrastructure\Curation\Entity
                        type:       xml

                    NotFoundStatus:
                        alias:      'NotFoundStatus'
                        dir:        '%kernel.project_dir%/config/model/curation'
                        is_bundle:  false
                        prefix:     App\Twitter\Infrastructure\Curation\Entity
                        type:       xml

                    OwnershipBatchCollectedEvent:
                        alias:      'OwnershipBatchCollectedEvent'
                        dir:        '%kernel.project_dir%/config/model/curation'
                        is_bundle:  false
                        prefix:     App\Twitter\Infrastructure\Curation\Entity
                        type:       xml

                    PublicationBatchCollectedEvent:
                        alias:      'PublicationBatchCollectedEvent'
                        dir:        '%kernel.project_dir%/config/model/curation'
                        is_bundle:  false
                        prefix:     App\Twitter\Infrastructure\Curation\Entity
                        type:       xml

                    Media:
                        alias:      'Media'
                        dir:        '%kernel.project_dir%/config/model/french-media-shareholders'
                        is_bundle:  false
                        prefix:     App\FrenchMediaShareholders\Entity
                        type:       xml

                    Owner:
                        alias:      'Owner'
                        dir:        '%kernel.project_dir%/config/model/french-media-shareholders'
                        is_bundle:  false
                        prefix:     App\FrenchMediaShareholders\Entity
                        type:       xml

                    Ownership:
                        alias:      'Ownership'
                        dir:        '%kernel.project_dir%/config/model/french-media-shareholders'
                        is_bundle:  false
                        prefix:     App\FrenchMediaShareholders\Entity
                        type:       xml

                    Member:
                        alias:      'Member'
                        dir:        '%kernel.project_dir%/config/model/member'
                        is_bundle:  false
                        prefix:     App\Membership\Infrastructure\Entity
                        type:       xml

                    Membership:
                        alias:      'Membership'
                        dir:        '%kernel.project_dir%/src/Membership/Infrastructure/Entity/Legacy'
                        is_bundle:  false
                        prefix:     App\Membership\Infrastructure\Entity\Legacy
                        type:       annotation

                    MemberInList:
                        alias:      'MemberInList'
                        dir:        '%kernel.project_dir%/config/model/member'
                        is_bundle:  false
                        prefix:     App\Membership\Infrastructure\Entity
                        type:       xml

                    MemberSubscription:
                        alias:      'MemberSubscription'
                        dir:        '%kernel.project_dir%/config/model/member'
                        is_bundle:  false
                        prefix:     App\Membership\Infrastructure\Entity
                        type:       xml

                    Popularity:
                        alias:      'Popularity'
                        dir:        '%kernel.project_dir%/config/model/popularity'
                        is_bundle:  false
                        prefix:     App\Twitter\Infrastructure\PublicationPopularity\Entity
                        type:       xml

                    Publication:
                        alias:      'Publication'
                        dir:        '%kernel.project_dir%/src/Twitter/Infrastructure/Publication/Entity'
                        is_bundle:  false
                        prefix:     App\Twitter\Infrastructure\Publication\Entity
                        type:       annotation

                    TimelyStatus:
                        alias:      'TimelyStatus'
                        dir:        '%kernel.project_dir%/config/model/publication-list'
                        is_bundle:  false
                        prefix:     App\Twitter\Infrastructure\PublishersList\Entity
                        type:       xml

                    ListSubscription:
                        alias:      'ListSubscription'
                        dir:        '%kernel.project_dir%/config/model/subscription'
                        is_bundle:  false
                        prefix:     App\Subscription\Infrastructure\Entity
                        type:       xml
