authentication_verify:
    path:     '/api/authentication/verify'
    defaults: { _controller: controller.authentication:verify }

highlight:
    path:     '/api/twitter/highlights'
    defaults: { _controller: controller.list:getHighlights }

aggregate:
    path:     '/api/twitter/admin/lists'
    defaults: { _controller: controller.list:getAggregates }

member:
    path:     '/api/twitter/admin/members'
    defaults: { _controller: controller.list:getMembers }

status:
    path:     '/api/twitter/admin/statuses'
    defaults: { _controller: controller.list:getStatuses }

bulk_collect_statuses:
    path:     '/api/twitter/admin/bulk-collect-statuses'
    defaults: { _controller: controller.list:bulkCollectAggregatesStatuses }
    methods:  [POST, OPTIONS]

collect:
    path:     '/api/twitter/admin/collect'
    defaults: { _controller: controller.list:requestCollection }
    methods:  [POST, OPTIONS]

unlock:
    path:     '/api/twitter/admin/unlock-aggregate'
    defaults: { _controller: controller.list:unlockAggregate }
    methods:  [POST, OPTIONS]

logged_in_member_profile:
    path:     '/api/twitter/admin/logged-in-member/profile'
    defaults: { _controller: controller.logged_in_member:getProfile }
    methods:  [POST, OPTIONS]

remove_aggregate:
    path:     '/api/twitter/admin/aggregate'
    defaults: { _controller: controller.aggregate:bulkRemoveAggregates }
    methods:  [POST, OPTIONS]

reset_total_members_for_aggregate:
    path:     '/api/twitter/admin/aggregate/reset-total-statuses'
    defaults: { _controller: controller.aggregate:resetTotalStatusesForAggregates }
    methods:  [POST, OPTIONS]

collect_statuses:
    path:     '/api/twitter/admin/aggregate/collect-statuses'
    defaults: { _controller: controller.aggregate:collectAggregatesStatuses }
    methods:  [POST, OPTIONS]

keywords:
    path:     '/api/twitter/admin/keywords'
    defaults: { _controller: controller.keyword:getKeywords }

kernel:
    resource: ../../src/Kernel.php
    type: annotation
