parameters:
    main_log_level: debug
    monolog_flat_logging_handler:
        type:     stream
        path:     "%kernel.logs_dir%/%kernel.environment%.log"
        level:    "%main_log_level%"
    monolog_json_logging_handler:
        type:     stream
        path:     "%kernel.logs_dir%/%kernel.environment%.json"
        level:    error
        formatter: monolog.json_formatter

monolog:
    handlers:
        main:
            type:    group
            action_level: debug
            members: [json, flat]
        json: '%monolog_json_logging_handler%'
        flat: '%monolog_flat_logging_handler%'
        console:
            type: console
            process_psr_3_messages: false
            channels: ["!event", "!doctrine"]
        deprecation:
            type: stream
            path: "%kernel.logs_dir%/%kernel.environment%.deprecations.log"
        deprecation_filter:
            type: filter
            handler: deprecation
            max_level: info
            channels: ["php"]

    channels: "%monolog_channels%"
