parameters:

    weaving_the_web_api.entity.token.class:         'WeavingTheWeb\Bundle\ApiBundle\Entity\Token'
    weaving_the_web_api.entity.whisperer.class:     'WeavingTheWeb\Bundle\ApiBundle\Entity\Whisperer'

services:
    repository.aggregate_subscription:
        factory:                                    [ '@doctrine.orm.entity_manager', 'getRepository' ]
        class:                                      'App\Member\Repository\AggregateSubscriptionRepository'
        arguments:
            - 'App\Member\Entity\AggregateSubscription'
        properties:
            accessor:                               "@weaving_the_web_twitter.api_accessor"
            logger:                                 '@logger'
            memberAggregateSubscriptionRepository:  '@repository.member_aggregate_subscription'
            memberSubscriptionRepository:           '@repository.member_subscription'
            networkRepository:                      '@repository.network'

    repository.authentication_token:
        factory: [ '@doctrine.orm.entity_manager', 'getRepository' ]
        class:   'App\Member\Repository\AuthenticationTokenRepository'
        arguments:
            - 'App\Member\Entity\AuthenticationToken'
        properties:
            memberRepository: "@user_manager"
            authenticator:    "@app.authenticator"

    repository.member_aggregate_subscription:
        factory: [ '@doctrine.orm.entity_manager', 'getRepository' ]
        class: 'App\Aggregate\Repository\MemberAggregateSubscriptionRepository'
        arguments:
            - 'App\Aggregate\Entity\MemberAggregateSubscription'

    repository.aggregate:
        factory: [ '@doctrine.orm.entity_manager', 'getRepository' ]
        class: 'WeavingTheWeb\Bundle\ApiBundle\Repository\AggregateRepository'
        arguments:
            - 'WeavingTheWeb\Bundle\ApiBundle\Entity\Aggregate'
        properties:
            amqpMessageProducer:    '@old_sound_rabbit_mq.weaving_the_web_amqp.twitter.aggregates_status_producer'
            logger:                 '@logger'
            statusRepository:       '@weaving_the_web_twitter.repository.status'
            timelyStatusRepository: '@repository.timely_status'
            tokenRepository:        '@weaving_the_web_api.repository.token'
            likedStatusRepository:  '@repository.liked_status'

    repository.highlight:
        factory: [ '@doctrine.orm.entity_manager', 'getRepository' ]
        class: 'App\Status\Repository\HighlightRepository'
        arguments:
            - 'App\Status\Entity\Highlight'
        properties:
            logger: '@logger'
            aggregate: '%highlight_aggregate_default%'

    repository.not_found_status:
        factory: [ '@doctrine.orm.entity_manager', 'getRepository' ]
        class: 'App\Status\Repository\NotFoundStatusRepository'
        arguments:
            - 'App\Status\Entity\NotFoundStatus'

    repository.timely_status:
        factory: [ '@doctrine.orm.entity_manager', 'getRepository' ]
        class: 'App\Aggregate\Repository\TimelyStatusRepository'
        arguments:
            - 'App\Aggregate\Entity\TimelyStatus'
        properties:
            statusRepository:    "@weaving_the_web_twitter.repository.status"

    repository.network:
        class:                            'App\Member\Repository\NetworkRepository'
        properties:
            accessor:                     "@weaving_the_web_twitter.api_accessor"
            entityManager:                "@doctrine.orm.entity_manager"
            logger:                       "@logger"
            memberRepository:             "@user_manager"
            memberSubscribeeRepository:   "@repository.member_subscribee"
            memberSubscriptionRepository: "@repository.member_subscription"

    repository.saved_search:
        factory: [ '@doctrine.orm.entity_manager', 'getRepository' ]
        class: 'App\Aggregate\Repository\SavedSearchRepository'
        arguments:
            - 'App\Aggregate\Entity\SavedSearch'

    repository.search_matching_status:
        factory: [ '@doctrine.orm.entity_manager', 'getRepository' ]
        class: 'App\Aggregate\Repository\SearchMatchingStatusRepository'
        arguments:
            - 'App\Aggregate\Entity\SearchMatchingStatus'
        properties:
            statusRepository: "@weaving_the_web_twitter.repository.status"
            logger:           "@logger"

    repository.liked_status:
        factory: [ '@doctrine.orm.entity_manager', 'getRepository' ]
        class: 'App\Status\Repository\LikedStatusRepository'
        arguments:
            - 'App\Status\Entity\LikedStatus'
        properties:
            memberRepository: "@user_manager"
            statusRepository: "@weaving_the_web_twitter.repository.status"

    repository.member_subscription:
        factory: [ '@doctrine.orm.entity_manager', 'getRepository' ]
        class: 'App\Member\Repository\MemberSubscriptionRepository'
        arguments:
            - 'App\Member\Entity\MemberSubscription'
        properties:
            memberRepository: "@user_manager"

    repository.member_subscribee:
        factory: [ '@doctrine.orm.entity_manager', 'getRepository' ]
        class: 'App\Member\Repository\MemberSubscribeeRepository'
        arguments:
            - 'App\Member\Entity\MemberSubscribee'
        properties:
            memberRepository: "@user_manager"

    weaving_the_web_api.repository.token:
        factory: [ '@doctrine.orm.entity_manager', 'getRepository' ]
        class: '%weaving_the_web_api.repository.token.class%'
        arguments:
            - '%weaving_the_web_api.entity.token.class%'

    weaving_the_web_api.repository.whisperer:
        factory: ['@doctrine.orm.entity_manager', 'getRepository' ]
        class: '%weaving_the_web_api.repository.whisperer.class%'
        arguments:
            - '%weaving_the_web_api.entity.whisperer.class%'
