---
- hosts: all
  sudo: true
  vars_files:
    - vars/all.yml
  roles:
    - role: git
      git_install_from_source: true
      git_install_path: "/usr"
      git_version: "2.1.0"
    - role: server
      tags: server
    - vagrant_local
    - role: apache
      tags: apache
    - varnish
    - role: mysql
      tags: mysql
    - role: phpmyadmin
      tags: phpmyadmin
    - role: rabbitmq
      tags: rabbitmq
    - elasticsearch
    - role: php
      tags: php
    - xdebug
    - composer
    - redis
    - role: nvm
      nvm:
        user: vagrant
        version: v0.29.0
        node_version: v4.2.2
    - app
